import {
  faSun,
  faMoon,
  faWater,
  faLeaf,
  faFire,
  faSnowflake,
  faMountain,
  faCity,
  faSpaceShuttle,
  faCoffee,
  faLemon,
  faGem,
  faUmbrellaBeach,
  faDragon,
  faUserNinja,
  faGuitar,
  faPaintBrush,
  faBook,
  faAppleAlt,
  faCandyCane,
  faGhost,
  faFlask,
  faRobot,
  faHeart,
  faSkull,
  faPaw,
  faFrog,
  faFeather,
  faCookie,
  faIceCream,
  faPizzaSlice,
  faGamepad,
  faChessKnight,
  faAtom,
  faMicrochip,
  faVirus,
  faDna,
  faWind,
  faCloudMoonRain,
  faMeteor,
  faCompass,
  faHatWizard,
  faGlassCheers,
  faCampground,
  faStore,
  faSchool,
  faIndustry,
  faLaptopCode,
  faBriefcaseMedical,
} from "@fortawesome/free-solid-svg-icons";

export const themes = [
  {
    id: "light",
    name: "Light Mode",
    description: "Crisp and clean light theme",
    icon: faSun,
    variables: {
      "--text-color": "#333333",
      "--background-color": "#f5f5f5",
      "--primary-color": "#007bff",
      "--secondary-color": "#6c757d",
      "--accent-color": "#28a745",
      "--sidebar-color": "#e9ecef",
      "--color-error": "#dc3545",
    },
  },
  {
    id: "dark",
    name: "Dark Mode",
    description: "Sleek dark theme",
    icon: faMoon,
    variables: {
      "--text-color": "#e0e0e0",
      "--background-color": "#121212",
      "--primary-color": "#bb86fc",
      "--secondary-color": "#03dac6",
      "--accent-color": "#cf6679",
      "--sidebar-color": "#1e1e1e",
      "--color-error": "#ff5252",
    },
  },
  {
    id: "ocean",
    name: "Ocean Blue",
    description: "Serene ocean-inspired theme",
    icon: faWater,
    variables: {
      "--text-color": "#e0f7fa",
      "--background-color": "#006064",
      "--primary-color": "#00acc1",
      "--secondary-color": "#26c6da",
      "--accent-color": "#ffd54f",
      "--sidebar-color": "#00838f",
      "--color-error": "#ff8a80",
    },
  },
  {
    id: "forest",
    name: "Forest Green",
    description: "Lush forest-inspired theme",
    icon: faLeaf,
    variables: {
      "--text-color": "#f1f8e9",
      "--background-color": "#1b5e20",
      "--primary-color": "#4caf50",
      "--secondary-color": "#81c784",
      "--accent-color": "#ffeb3b",
      "--sidebar-color": "#2e7d32",
      "--color-error": "#ff8a65",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm sunset-inspired theme",
    icon: faFire,
    variables: {
      "--text-color": "#fff3e0",
      "--background-color": "#bf360c",
      "--primary-color": "#ff5722",
      "--secondary-color": "#ff8a65",
      "--accent-color": "#ffd54f",
      "--sidebar-color": "#d84315",
      "--color-error": "#d50000",
    },
  },
  {
    id: "arctic",
    name: "Arctic Frost",
    description: "Cool and crisp arctic theme",
    icon: faSnowflake,
    variables: {
      "--text-color": "#263238",
      "--background-color": "#eceff1",
      "--primary-color": "#4fc3f7",
      "--secondary-color": "#81d4fa",
      "--accent-color": "#ff8a65",
      "--sidebar-color": "#cfd8dc",
      "--color-error": "#ef5350",
    },
  },
  {
    id: "mountain",
    name: "Mountain Majesty",
    description: "Majestic mountain-inspired theme",
    icon: faMountain,
    variables: {
      "--text-color": "#eceff1",
      "--background-color": "#37474f",
      "--primary-color": "#7986cb",
      "--secondary-color": "#9fa8da",
      "--accent-color": "#ffcc80",
      "--sidebar-color": "#455a64",
      "--color-error": "#ef5350",
    },
  },
  {
    id: "neonCity",
    name: "Neon City",
    description: "Vibrant neon city theme",
    icon: faCity,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#1a1a2e",
      "--primary-color": "#ff00ff",
      "--secondary-color": "#00ffff",
      "--accent-color": "#ffff00",
      "--sidebar-color": "#16213e",
      "--color-error": "#ff0000",
    },
  },
  {
    id: "spaceExplorer",
    name: "Space Explorer",
    description: "Cosmic space exploration theme",
    icon: faSpaceShuttle,
    variables: {
      "--text-color": "#e0e0e0",
      "--background-color": "#0c0c1d",
      "--primary-color": "#6a00ff",
      "--secondary-color": "#00b8d4",
      "--accent-color": "#ffea00",
      "--sidebar-color": "#1c1c2d",
      "--color-error": "#ff5252",
    },
  },
  {
    id: "coffeeBreak",
    name: "Coffee Break",
    description: "Warm and cozy coffee-inspired theme",
    icon: faCoffee,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#3e2723",
      "--primary-color": "#795548",
      "--secondary-color": "#a1887f",
      "--accent-color": "#ffc107",
      "--sidebar-color": "#4e342e",
      "--color-error": "#ff5722",
    },
  },
  {
    id: "lemonadeStand",
    name: "Lemonade Stand",
    description: "Fresh and zesty lemon-inspired theme",
    icon: faLemon,
    variables: {
      "--text-color": "#1a237e",
      "--background-color": "#fff9c4",
      "--primary-color": "#fdd835",
      "--secondary-color": "#fff176",
      "--accent-color": "#4caf50",
      "--sidebar-color": "#fff59d",
      "--color-error": "#f44336",
    },
  },
  {
    id: "amethystDream",
    name: "Amethyst Dream",
    description: "Rich and regal amethyst-inspired theme",
    icon: faGem,
    variables: {
      "--text-color": "#f3e5f5",
      "--background-color": "#4a148c",
      "--primary-color": "#9c27b0",
      "--secondary-color": "#ba68c8",
      "--accent-color": "#ffd54f",
      "--sidebar-color": "#6a1b9a",
      "--color-error": "#ff4081",
    },
  },
  {
    id: "tropicalParadise",
    name: "Tropical Paradise",
    description: "Vibrant tropical-inspired theme",
    icon: faUmbrellaBeach,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#1b5e20",
      "--primary-color": "#00c853",
      "--secondary-color": "#69f0ae",
      "--accent-color": "#ff6d00",
      "--sidebar-color": "#2e7d32",
      "--color-error": "#ff3d00",
    },
  },
  {
    id: "dragonRealm",
    name: "Dragon Realm",
    description: "Mythical dragon-inspired theme",
    icon: faDragon,
    variables: {
      "--text-color": "#fafafa",
      "--background-color": "#1a2f3f",
      "--primary-color": "#ff6b6b",
      "--secondary-color": "#feca57",
      "--accent-color": "#54a0ff",
      "--sidebar-color": "#2c3e50",
      "--color-error": "#ff5252",
    },
  },
  {
    id: "ninjaWhisper",
    name: "Ninja Whisper",
    description: "Stealthy ninja-inspired theme",
    icon: faUserNinja,
    variables: {
      "--text-color": "#c8c8c8",
      "--background-color": "#1c1c1c",
      "--primary-color": "#6b6b6b",
      "--secondary-color": "#4a4a4a",
      "--accent-color": "#ff4081",
      "--sidebar-color": "#2a2a2a",
      "--color-error": "#ff6b6b",
    },
  },
  {
    id: "rockStar",
    name: "Rock Star",
    description: "Energetic rock music-inspired theme",
    icon: faGuitar,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#000000",
      "--primary-color": "#ff0000",
      "--secondary-color": "#ffff00",
      "--accent-color": "#00ffff",
      "--sidebar-color": "#1a1a1a",
      "--color-error": "#ff69b4",
    },
  },
  {
    id: "artGallery",
    name: "Art Gallery",
    description: "Artistic and colorful theme",
    icon: faPaintBrush,
    variables: {
      "--text-color": "#333333",
      "--background-color": "#f0f0f0",
      "--primary-color": "#e74c3c",
      "--secondary-color": "#3498db",
      "--accent-color": "#2ecc71",
      "--sidebar-color": "#ecf0f1",
      "--color-error": "#e67e22",
    },
  },
  {
    id: "libraryQuiet",
    name: "Library Quiet",
    description: "Calm and studious library theme",
    icon: faBook,
    variables: {
      "--text-color": "#2c3e50",
      "--background-color": "#ecf0f1",
      "--primary-color": "#34495e",
      "--secondary-color": "#7f8c8d",
      "--accent-color": "#16a085",
      "--sidebar-color": "#bdc3c7",
      "--color-error": "#c0392b",
    },
  },
  {
    id: "appleOrchard",
    name: "Apple Orchard",
    description: "Fresh and crisp apple-inspired theme",
    icon: faAppleAlt,
    variables: {
      "--text-color": "#1e1e1e",
      "--background-color": "#f0fff0",
      "--primary-color": "#4caf50",
      "--secondary-color": "#8bc34a",
      "--accent-color": "#ff5722",
      "--sidebar-color": "#e8f5e9",
      "--color-error": "#f44336",
    },
  },
  {
    id: "candyLand",
    name: "Candy Land",
    description: "Sweet and colorful candy-inspired theme",
    icon: faCandyCane,
    variables: {
      "--text-color": "#4a0e4e",
      "--background-color": "#fff0f5",
      "--primary-color": "#ff69b4",
      "--secondary-color": "#00ced1",
      "--accent-color": "#ff6347",
      "--sidebar-color": "#ffc0cb",
      "--color-error": "#ff4500",
    },
  },
  {
    id: "hauntedMansion",
    name: "Haunted Mansion",
    description: "Spooky and mysterious theme",
    icon: faGhost,
    variables: {
      "--text-color": "#b0bec5",
      "--background-color": "#263238",
      "--primary-color": "#6a1b9a",
      "--secondary-color": "#4a148c",
      "--accent-color": "#ff9800",
      "--sidebar-color": "#37474f",
      "--color-error": "#d50000",
    },
  },
  {
    id: "madScientist",
    name: "Mad Scientist",
    description: "Eccentric laboratory-inspired theme",
    icon: faFlask,
    variables: {
      "--text-color": "#e0e0e0",
      "--background-color": "#1a237e",
      "--primary-color": "#00bcd4",
      "--secondary-color": "#4caf50",
      "--accent-color": "#ffeb3b",
      "--sidebar-color": "#283593",
      "--color-error": "#f44336",
    },
  },
  {
    id: "roboticFuture",
    name: "Robotic Future",
    description: "Futuristic robot-inspired theme",
    icon: faRobot,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#212121",
      "--primary-color": "#00bfa5",
      "--secondary-color": "#64ffda",
      "--accent-color": "#ffd54f",
      "--sidebar-color": "#424242",
      "--color-error": "#ff5252",
    },
  },
  {
    id: "lovelyPink",
    name: "Lovely Pink",
    description: "Soft and romantic pink theme",
    icon: faHeart,
    variables: {
      "--text-color": "#4a0e4e",
      "--background-color": "#fff0f5",
      "--primary-color": "#ff69b4",
      "--secondary-color": "#ff9ff3",
      "--accent-color": "#ff1493",
      "--sidebar-color": "#ffc0cb",
      "--color-error": "#ff4081",
    },
  },
  {
    id: "skullAndBones",
    name: "Skull and Bones",
    description: "Edgy skull-inspired theme",
    icon: faSkull,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#000000",
      "--primary-color": "#ffffff",
      "--secondary-color": "#424242",
      "--accent-color": "#ff0000",
      "--sidebar-color": "#212121",
      "--color-error": "#ff5252",
    },
  },
  {
    id: "pawsAndWhiskers",
    name: "Paws and Whiskers",
    description: "Cute pet-inspired theme",
    icon: faPaw,
    variables: {
      "--text-color": "#4e342e",
      "--background-color": "#ffebee",
      "--primary-color": "#ff8a65",
      "--secondary-color": "#a1887f",
      "--accent-color": "#81c784",
      "--sidebar-color": "#ffcdd2",
      "--color-error": "#ff5252",
    },
  },
  {
    id: "enchantedForest",
    name: "Enchanted Forest",
    description: "Magical forest-inspired theme",
    icon: faFrog,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#1b5e20",
      "--primary-color": "#4caf50",
      "--secondary-color": "#81c784",
      "--accent-color": "#ffeb3b",
      "--sidebar-color": "#2e7d32",
      "--color-error": "#ff8a65",
    },
  },
  {
    id: "featherLight",
    name: "Feather Light",
    description: "Soft and airy feather-inspired theme",
    icon: faFeather,
    variables: {
      "--text-color": "#424242",
      "--background-color": "#fafafa",
      "--primary-color": "#90a4ae",
      "--secondary-color": "#b0bec5",
      "--accent-color": "#4dd0e1",
      "--sidebar-color": "#eceff1",
      "--color-error": "#ff8a65",
    },
  },
  {
    id: "cookieMonster",
    name: "Cookie Monster",
    description: "Fun cookie-inspired theme",
    icon: faCookie,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#0277bd",
      "--primary-color": "#4fc3f7",
      "--secondary-color": "#81d4fa",
      "--accent-color": "#795548",
      "--sidebar-color": "#039be5",
      "--color-error": "#ff8a65",
    },
  },
  {
    id: "iceCreamDream",
    name: "Ice Cream Dream",
    description: "Sweet ice cream-inspired theme",
    icon: faIceCream,
    variables: {
      "--text-color": "#3e2723",
      "--background-color": "#fff8e1",
      "--primary-color": "#ffcc80",
      "--secondary-color": "#fff176",
      "--accent-color": "#f48fb1",
      "--sidebar-color": "#ffecb3",
      "--color-error": "#ff8a65",
    },
  },
  {
    id: "pizzaNight",
    name: "Pizza Night",
    description: "Delicious pizza-inspired theme",
    icon: faPizzaSlice,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#b71c1c",
      "--primary-color": "#ff8a65",
      "--secondary-color": "#ffeb3b",
      "--accent-color": "#4caf50",
      "--sidebar-color": "#c62828",
      "--color-error": "#ff5252",
    },
  },
  {
    id: "gamingZone",
    name: "Gaming Zone",
    description: "Exciting gaming-inspired theme",
    icon: faGamepad,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#1a237e",
      "--primary-color": "#00c853",
      "--secondary-color": "#ff6d00",
      "--accent-color": "#d500f9",
      "--sidebar-color": "#283593",
      "--color-error": "#ff1744",
    },
  },
  {
    id: "chessmaster",
    name: "Chessmaster",
    description: "Strategic chess-inspired theme",
    icon: faChessKnight,
    variables: {
      "--text-color": "#212121",
      "--background-color": "#f5f5f5",
      "--primary-color": "#616161",
      "--secondary-color": "#9e9e9e",
      "--accent-color": "#ffc107",
      "--sidebar-color": "#e0e0e0",
      "--color-error": "#d32f2f",
    },
  },
  {
    id: "atomicAge",
    name: "Atomic Age",
    description: "Scientific atom-inspired theme",
    icon: faAtom,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#311b92",
      "--primary-color": "#7c4dff",
      "--secondary-color": "#b388ff",
      "--accent-color": "#76ff03",
      "--sidebar-color": "#4527a0",
      "--color-error": "#ff1744",
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    description: "Futuristic cyberpunk-inspired theme",
    icon: faMicrochip,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#000000",
      "--primary-color": "#00ffff",
      "--secondary-color": "#ff00ff",
      "--accent-color": "#ffff00",
      "--sidebar-color": "#1a1a1a",
      "--color-error": "#ff0000",
    },
  },
  {
    id: "biohazard",
    name: "Biohazard",
    description: "Intense biohazard-inspired theme",
    icon: faVirus,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#1b1b1b",
      "--primary-color": "#ffff00",
      "--secondary-color": "#000000",
      "--accent-color": "#ff0000",
      "--sidebar-color": "#2e2e2e",
      "--color-error": "#ff4d4d",
    },
  },
  {
    id: "dnaSequence",
    name: "DNA Sequence",
    description: "Scientific DNA-inspired theme",
    icon: faDna,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#0d47a1",
      "--primary-color": "#2196f3",
      "--secondary-color": "#64b5f6",
      "--accent-color": "#ff4081",
      "--sidebar-color": "#1565c0",
      "--color-error": "#ff5252",
    },
  },
  {
    id: "tropicalStorm",
    name: "Tropical Storm",
    description: "Dynamic tropical storm-inspired theme",
    icon: faCloudMoonRain,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#263238",
      "--primary-color": "#00acc1",
      "--secondary-color": "#4dd0e1",
      "--accent-color": "#ffd54f",
      "--sidebar-color": "#37474f",
      "--color-error": "#ff8a65",
    },
  },
  {
    id: "desertWind",
    name: "Desert Wind",
    description: "Warm and sandy desert-inspired theme",
    icon: faWind,
    variables: {
      "--text-color": "#3e2723",
      "--background-color": "#fbe9e7",
      "--primary-color": "#ff5722",
      "--secondary-color": "#ffab91",
      "--accent-color": "#ffd54f",
      "--sidebar-color": "#ffccbc",
      "--color-error": "#d50000",
    },
  },
  {
    id: "meteorShower",
    name: "Meteor Shower",
    description: "Celestial meteor-inspired theme",
    icon: faMeteor,
    variables: {
      "--text-color": "#e0e0e0",
      "--background-color": "#1a237e",
      "--primary-color": "#7c4dff",
      "--secondary-color": "#b388ff",
      "--accent-color": "#ffeb3b",
      "--sidebar-color": "#283593",
      "--color-error": "#ff4081",
    },
  },
  {
    id: "explorerCompass",
    name: "Explorer's Compass",
    description: "Adventure-inspired compass theme",
    icon: faCompass,
    variables: {
      "--text-color": "#3e2723",
      "--background-color": "#fff3e0",
      "--primary-color": "#795548",
      "--secondary-color": "#a1887f",
      "--accent-color": "#ffc107",
      "--sidebar-color": "#ffe0b2",
      "--color-error": "#f44336",
    },
  },
  {
    id: "wizardAcademy",
    name: "Wizard Academy",
    description: "Magical wizard-inspired theme",
    icon: faHatWizard,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#1a237e",
      "--primary-color": "#7c4dff",
      "--secondary-color": "#b388ff",
      "--accent-color": "#ffd700",
      "--sidebar-color": "#283593",
      "--color-error": "#ff4081",
    },
  },
  {
    id: "cocktailParty",
    name: "Cocktail Party",
    description: "Vibrant cocktail-inspired theme",
    icon: faGlassCheers,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#6a1b9a",
      "--primary-color": "#e91e63",
      "--secondary-color": "#f48fb1",
      "--accent-color": "#ffeb3b",
      "--sidebar-color": "#8e24aa",
      "--color-error": "#ff5252",
    },
  },
  {
    id: "campfireNights",
    name: "Campfire Nights",
    description: "Cozy campfire-inspired theme",
    icon: faCampground,
    variables: {
      "--text-color": "#fafafa",
      "--background-color": "#3e2723",
      "--primary-color": "#ff5722",
      "--secondary-color": "#ff8a65",
      "--accent-color": "#ffd54f",
      "--sidebar-color": "#4e342e",
      "--color-error": "#ff8a65",
    },
  },
  {
    id: "vintageShop",
    name: "Vintage Shop",
    description: "Nostalgic vintage store theme",
    icon: faStore,
    variables: {
      "--text-color": "#3e2723",
      "--background-color": "#efebe9",
      "--primary-color": "#795548",
      "--secondary-color": "#a1887f",
      "--accent-color": "#4caf50",
      "--sidebar-color": "#d7ccc8",
      "--color-error": "#f44336",
    },
  },
  {
    id: "schoolDays",
    name: "School Days",
    description: "Classic school-inspired theme",
    icon: faSchool,
    variables: {
      "--text-color": "#212121",
      "--background-color": "#f5f5f5",
      "--primary-color": "#1976d2",
      "--secondary-color": "#64b5f6",
      "--accent-color": "#ffc107",
      "--sidebar-color": "#e0e0e0",
      "--color-error": "#e53935",
    },
  },
  {
    id: "industrialAge",
    name: "Industrial Age",
    description: "Rugged industrial-inspired theme",
    icon: faIndustry,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#263238",
      "--primary-color": "#607d8b",
      "--secondary-color": "#90a4ae",
      "--accent-color": "#ff5722",
      "--sidebar-color": "#37474f",
      "--color-error": "#f44336",
    },
  },
  {
    id: "codeNinja",
    name: "Code Ninja",
    description: "Sleek coding-inspired theme",
    icon: faLaptopCode,
    variables: {
      "--text-color": "#e0e0e0",
      "--background-color": "#212121",
      "--primary-color": "#00bcd4",
      "--secondary-color": "#4dd0e1",
      "--accent-color": "#ffeb3b",
      "--sidebar-color": "#424242",
      "--color-error": "#ff5252",
    },
  },
  {
    id: "hospitalityBlue",
    name: "Hospitality Blue",
    description: "Calming medical-inspired theme",
    icon: faBriefcaseMedical,
    variables: {
      "--text-color": "#ffffff",
      "--background-color": "#0277bd",
      "--primary-color": "#03a9f4",
      "--secondary-color": "#4fc3f7",
      "--accent-color": "#ffd54f",
      "--sidebar-color": "#0288d1",
      "--color-error": "#ff8a65",
    },
  },
];
